language: python
python:
- '3.6'
- '3.5'
- '3.4'

matrix:
  include:
    - python: 3.6
      sudo: required
      dist: trusty
      env:
      - TOXENV=style
      before_install:
      - sudo sed -i 's/trusty/yakkety/' /etc/apt/sources.list
      - sudo rm -rf /etc/apt/sources.list.d/*
      - sudo apt-get -qq update && sudo apt-get -qq install shellcheck

cache:
  directories:
  - $HOME/.cache/pip
  - .eggs

install:
- pip install --upgrade pip setuptools
- pip install tox-travis

script: tox

branches:
  only:
    - explorer
